### ISSUE TITLE
Feature: Hide network change options (Was BUG: Network change not supported)

### ISSUE THREAD

**Issue by claireolmstead** [frequency-chain/testnet-faucet#21]
https://github.com/user-attachments/assets/f0803ef2-fb4f-451f-9aa6-30f4eef61808

## Acceptance Criteria:
- each network should take us to the correct network rather than displaying an unknown page or the incorrect network.

**Comment by shannonwells** [comment]
Since we have only the one faucet, and the "network" selection is left over from Parity code intended to support multiple Polkadot networks (Polkadot, Rococo, Paseo, etc), the solution should just be to either get rid of the dropdown entirely or to remove all selections but Paseo.  Even a Chain dropdown doesn't make sense.  Then if we decide to support a mainnet faucet we can add a configuration later.

**Comment by wilwade** [comment]
@claireolmstead / @shannonwells We can remove the dropdowns. I wanted them to keep working when it was a "version" of the faucet, but with the color and style changes let's hide it.
